### ISSUE TITLE
No examples

### ISSUE THREAD

**Issue by Pidroh** [cedx/bootstrap.hx#2]
There are no examples of working pages using the library. This may have a bigger priority than documentation because most users can get around with just an example.

(I'm kinda new to both Bootstrap and Haxe. Would be really cool if we had an example. No idea if should try to make up the UI through code or maybe build my UI on HTML and somehow access it through Haxe?)

**Comment by cedx** [comment]
There is no real difference between the official Bootstrap library and this package.
When using the official Bootstrap library:
1. You add the Bootstrap files to your project, either through a [CDN](https://www.jsdelivr.com/package/npm/bootstrap) or through a [Node.js module](https://www.npmjs.com/package/bootstrap).
2. You create your HTML code by following the [Bootstrap documentation](https://getbootstrap.com/docs/).
3. **Eventually**, you use the JavaScript API to customize the behavior of some components.

When using this package:
1. You add this package as a dependency of your project, with [Haxelib](https://lib.haxe.org/documentation/using-haxelib/) or [lix](https://github.com/lix-pm/lix.client) package manager. In a command prompt, try `haxelib install bootstrap_bundle` (or `lix +lib bootstrap_bundle`).
2. You add the Bootstrap files to your project through the provided commande line interface. In a command prompt, try `haxelib run bootstrap_bundle --help` (or `lix run bootstrap_bundle --help`) to see the available commands. Most of the time, you'll use the `copy` command: `haxelib run bootstrap_bundle copy --help`.
3. You create your HTML code by following the [Bootstrap documentation](https://getbootstrap.com/docs/).
4. **Eventually**, you use the JavaScript API, through the provided [Haxe externs](https://haxe.org/manual/lf-externs.html), to customize the behavior of some components.

An overview of the API exposed by the Haxe externs is available here:
https://cedx.github.io/bootstrap.hx/api/

I really need to create the documentation for a more useful explanation 😄 
In the meantime, I've added some code samples in the [`example` folder](https://github.com/cedx/bootstrap.hx/tree/main/example), corresponding to the components that have dedicated JavaScript API/Haxe externs.

In these samples, the UI is provided by the `render()` function, but in a real-world project, the UI would be provided by plain HTML code (i.e. you don't need to use Haxe to create the UI).

**Comment by cedx** [comment]
I close this issue because what is really missing is a complete documentation.
See issue #1 for a follow-up.
